spring:
  application:
    name: ef-message
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.150.105:8848 # Nacos地址
        namespace: easyfun_dev
        file-extension: yaml
        username: nacos
        password: 12345678
  config:
    import:
      - optional:nacos:ef-custom
      - optional:nacos:ef-message
      - optional:nacos:ef-message-${spring.profiles.active}
      - optional:nacos:ef-nacos
#      - optional:nacos:ef-mysql
      - optional:nacos:ef-redis
#      - optional:nacos:ef-mybatis
      - optional:nacos:ef-jackson
      - optional:nacos:ef-jwt
      - optional:nacos:ef-rabbitmq
